### ISSUE TITLE
pip install missing requirements

### ISSUE THREAD

**Issue by dougbot01** [bryantbhowell/tableau_tools#22]
It appears this package doesn't work without psycopg2

>>> from tableau_tools import Tabcmd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Tabcmd'
>>> from tableau_tools import tabcmd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/env/lib/python3.6/site-packages/tableau_tools/tabcmd.py", line 6, in <module>
    from tableau_tools.tableau_repository import *
  File "~/env/lib/python3.6/site-packages/tableau_tools/tableau_repository.py", line 5, in <module>
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'

**Comment by bryanthowell-tableau** [comment]
Since the majority of people don't use the TableauRepository or Tabcmd classes, I've decided to leave the psycopg2 requirements at optional. They just require a quick pip install.
