### ISSUE TITLE
Unable to publish large workbook - 400 Bad Request

### ISSUE THREAD

**Issue by sanjay-varanasi** [bryantbhowell/tableau_tools#23]
Tableau_tools version: 4.4.1.
OS: MacOs High Sierra 10.13.4
Python: 2.7.10

I'm using an [example](https://github.com/bryantbhowell/tableau_tools/blob/4.0.0/examples/move_extracts_from_server_to_server.py) in this repo. Original file uses TableauRestApiConnection25 which results in the same error as when it is modified to using TableauRestApiConnection28.

Publishing a small <10MB workbook works just fine. Uploading a 100MB+ workbook results in an error like so:

```
$ python copy-extract-large.py
  Error: File 'temp_wb.twbx' cannot be opened to upload
  Traceback (most recent call last):
    File "copy-extract-large.py", line 31, in <module>
      d.publish_workbook(u'{}.twbx'.format(downloaded_filename), wb_name_on_server, proj, save_credentials=False, overwrite=True)
    File "/Users/svaranasi/WorkDir/py27venv/scheduler/lib/python2.7/site-packages/tableau_tools/tableau_rest_api/tableau_rest_api_connection.py", line 1946, in publish_workbook
      check_published_ds=check_published_ds)
    File "/Users/svaranasi/WorkDir/py27venv/scheduler/lib/python2.7/site-packages/tableau_tools/tableau_rest_api/tableau_rest_api_connection.py", line 2077, in publish_content
      return self.send_publish_request(url, publish_request, boundary_string)
    File "/Users/svaranasi/WorkDir/py27venv/scheduler/lib/python2.7/site-packages/tableau_tools/tableau_rest_api/tableau_rest_api_connection.py", line 367, in send_publish_request
      api.request_from_api(0)
    File "/Users/svaranasi/WorkDir/py27venv/scheduler/lib/python2.7/site-packages/tableau_tools/tableau_rest_api/rest_xml_request.py", line 285, in request_from_api
      self.__make_request(page_number)
    File "/Users/svaranasi/WorkDir/py27venv/scheduler/lib/python2.7/site-packages/tableau_tools/tableau_rest_api/rest_xml_request.py", line 200, in __make_request
      response.raise_for_status()
    File "/Users/svaranasi/WorkDir/py27venv/scheduler/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
      raise HTTPError(http_error_msg, response=self)
  requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://<snipped>/api/2.8/sites/8fui90b6-61e7-40a4-8b27-3a1971caef0e/workbooks?uploadSessionId=228:3A71C112761E4547BG872YZ562FP5D54-2:0&workbookType=twbx&overwrite=true
```

The error   **_Error: File 'temp_wb.twbx' cannot be opened to upload_** is strange because I can surely see the script creating this file and deleting it as part of the copy.

I've also checked Tableau's REST API docs for [Publish Workbook](https://onlinehelp.tableau.com/current/api/rest_api/en-us/help.htm#REST/rest_api_ref.htm#Publish_Workbook%3FTocPath%3DAPI%2520Reference%7C_____54) and the URL and params seems to be to spec.

The logs show the part files uploading successfully (PUT operations). It is the final "send_publish_request" that is failing.

The log file has this:

```
2018-04-10 15:07:32 : Received a 400 error, here was response:
2018-04-10 15:07:32 : <?xml version='1.0' encoding='UTF-8'?><tsResponse xmlns="http://tableau.com/api" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://tableau.com/api http://tableau.com/api/ts-api-2.8.xsd"><error code="400011"><summary>Bad Request</summary><detail>There was a problem publishing the file '29187:9B137D4FF84945D4BE55B9E1F21772C8-1:0'.</detail></error></tsResponse>
2018-04-10 15:07:32 : Tableau REST API error code is: 400011
```
I added additional logging in the rest_xml_request.py file and here's line 156, 157 in the file after my change:
```
self.log(u"HERE#3 !"+url+"DATA"+str(self.__publish_content)+"HEADERS"+str(request_headers))                        
response = requests.post(url, data=self.__publish_content, headers=request_headers)

```
I see that the request looks OK to my eyes. Here's the logs:

```
DATA
--0d6a88bdf4b5c30b09ca46e16958c7
Content-Disposition: name="request_payload"
Content-Type: text/xml

<tsRequest>
<workbook name="Workbook Example" showTabs="true">
<project id="ea62d37c-11m6-11e8-8b28-bf4e547648ce" />
</workbook></tsRequest>
--0d6a88bdf4b5c30b09ca46e16958c7

--HEADERS{'X-tableau-auth': 'op42_abcQ--JSvrKm7yvZw|iV9pvJeGt8q5I2b7Ntg1l4pEq6JZlXYZ', 'Content-Type': 'multipart/mixed; boundary=0d6a88bdf4b5c30b09ca46e16958c7'}
```

(^ Tokens and IDs have been slightly modified when pasting here for security reasons)

Please help!

**Comment by bryanthowell-tableau** [comment]
Hi Sanjay -- I made some updates to the publishing code in the 4.5.0 release. Can you upgrade and tell me if you are still seeing these issues?

**Comment by sanjay-varanasi** [comment]
Unfortunately, that did not help.

Here's what I see now:

> Traceback (most recent call last):
>   File "Tableau-Project/Scripts/copy-extract-large.py", line 24, in <module>
>     t.download_workbook(wb_name_on_server, downloaded_filename, proj_name_or_luid=proj_name)
>   File "/Users/svaranasi/WorkDir/Tableau-Project/lib/python2.7/site-packages/tableau_tools/tableau_rest_api/tableau_rest_api_connection.py", line 1160, in download_workbook
>     save_file.write(wb)
> TypeError: must be string or buffer, not Element

**Comment by bryanthowell-tableau** [comment]
I believe we determined this was an issue with oauth credentials rather than the file sizes. I've added in the oath flag to the publish methods in 4.6.2 and it will be available then. There still may be issues with oAuth when publishing via the REST API on occasion due to other oAuth considerations
